#!/usr/bin/env bash
## Matyas Sway — Rofi application launcher
## Bound to: $mod+d, $alt+F1

DIR="$HOME/.config/sway"
RASI="$DIR/rofi/launcher.rasi"

exec rofi -show drun -me-select-entry "" -me-accept-entry MousePrimary -theme "$RASI"
