## Matyas Sway — Kitty fonts

font_family      Noto Sans Mono
bold_font        Noto Sans Mono Bold
italic_font      Noto Sans Mono Italic
bold_italic_font Noto Sans Mono Bold Italic

# Nerd Font fallback for glyphs (bar icons, symbols, etc.)
symbol_map U+E000-U+F8FF,U+F0000-U+FFFFF Symbols Nerd Font

font_size 10
force_ltr no
